name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
 
trigger:
  branches:
    include:
    - main
    - azure-pipelines
 
pr: none
 
variables:
  buildConfiguration: 'Release'
  BUILDPLATFORM: 'linux/amd64'
  REGISTRY: msgraphprodregistry.azurecr.io # Azure Container Registry
  IMAGE_NAME: public/openapi/kiota       # Docker image name
  PREVIEW_BRANCH: "refs/heads/main"      # Branch for preview builds

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
 
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      vmImage: ubuntu-latest
    stages:
    - stage: Build
      jobs:
        - job: build
          steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 9'
            inputs:
              version: 9.x
        - job: validate_docker_build
          displayName: Validate Docker Build
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            vmImage: ubuntu-latest
          steps:
            # Enable QEMU for multi-architecture builds
            # - script: |
            #     docker run --rm multiarch/qemu-user-static --reset -p yes
            #   displayName: Enable QEMU for multi-arch
            - script: |
                docker version
                docker info
              displayName: Show docker environment
            # Build Docker image for validation (no push)
            - task: 1ES.BuildContainerImage@1
              inputs:
                image: $(REGISTRY)/$(IMAGE_NAME):validation    # Image name to build (including a tag). Required. Alias: localImage
                path: $(Build.SourcesDirectory)                 # Required. Alias: context
                dockerfile: ./Dockerfile             # Optional. Default: 'contextPath/Dockerfile'
                # buildArguments: --build-arg BUILDPLATFORM=$(BUILDPLATFORM) # --platform linux/amd64,linux/arm64/v8         # Optional. Default: ''
                # enableNetwork: true                         # Optional. Default: false
                # enablePull: true                           # Optional. Default: true
                # enableCache: true                           # Optional. Default: false
                # useBuildKit: true                           # Optional. Default: false