trigger:
  branches:
    include:
      - 'task/update-acr-pipeline'
  tags:
    include:
      - v*
schedules:
  - cron: "0 18 * * 4"
    displayName: "Weekly Publish Docker Image"
    branches:
      include:
        - main
    always: true

variables:
  REGISTRY: "msgraphprodregistry.azurecr.io"
  IMAGE_NAME: "public/openapi/kiota"
  PREVIEW_BRANCH: "refs/heads/main"

stages:
    - stage: Build docker image
      jobs:
          - job: Build
            steps:
            - task: Docker@2
              displayName: Build the docker image
              inputs:
                command: 'build'
                Dockerfile: '**/Dockerfile'
                  
    